### ISSUE TITLE
Weather API is broken

### ISSUE THREAD

**Issue by evaboogaard** [evaboogaard/blok-tech-team#82] opened 2022-04-05 09:51 UTC
Oh no, our most valuable asset, how can we ever survive this catastrophe???

No but fr, it doesn't work anymore, I can only see this:

<img width="84" alt="Schermafbeelding 2022-04-05 om 11 51 12" src="https://user-images.githubusercontent.com/94062754/161728048-087b3269-9b5a-44be-aabf-c0a8649a7951.png">

Where our beautiful weather icon used to be.

Anyone know what's going on ?

**Comment by maxvl3** [comment] 2022-04-05 11:58
The problem is probably due to helmet. Helmet's security is blocking certain actions. My filter also has some problems because of this

**Comment by evaboogaard** [comment] 2022-04-05 12:27
Alright I'm assigning this to @Davi9898 then, since Helmet is your topic. If I can do anything to help, lmk

**Comment by PipHarsveld** [comment] 2022-04-06 19:20
Reopening this issue because the weather api doesn't work on Heroku :,(

**Comment by PipHarsveld** [comment] 2022-04-06 19:40
Fixed by @maxvl3

**Closed by PipHarsveld** 2022-04-06 19:40 UTC
Labels: bug, help wanted
